
/* Drop Tables */

DROP TABLE RXT.T_PAYMENT_CHANNEL CASCADE CONSTRAINTS;
DROP TABLE RXT.T_PAYMENT_CHANNEL_ACCT_REL CASCADE CONSTRAINTS;
DROP TABLE RXT.T_PAYMENT_CHANNEL_BANK CASCADE CONSTRAINTS;




/* Create Tables */

-- 支付渠道表
CREATE TABLE RXT.T_PAYMENT_CHANNEL
(
	-- 主键
	ID varchar2(20 char) NOT NULL,
	-- 支付通道代码
	PAY_CHANNEL_ID varchar2(20 char),
	-- 支付通道名称
	PAY_CHANNEL_NAME varchar2(200 char),
	-- 支付方式，1-网银支付；2-快捷支付;5-扫码支付
	PAY_MODE varchar2(2 char),
	-- 第三方支付默认手续费率
	FEE_RATE varchar2(14 char),
	-- 默认手续费上限（单位：分）
	MAX_FEE varchar2(14 char),
	-- 默认手续费下限（单位：分）
	MIN_FEE varchar2(14 char),
	-- 清算天数
	SETTLE_DAYS varchar2(3 char),
	CONSTRAINT PK_PAYMENT_CHANNEL PRIMARY KEY (ID)
);


-- 渠道与结算账户关系表
CREATE TABLE RXT.T_PAYMENT_CHANNEL_ACCT_REL
(
	-- 主键ID
	ID varchar2(20 char) NOT NULL,
	-- 支付渠道表ID
	T_PAYMENT_CHANNEL_ID varchar2(20 char),
	-- 结算账户信息表ID
	T_ZJGJ_SETTLE_ACCT_ID varchar2(20 char),
	CONSTRAINT PRI_T_PAYMENT_CHANNEL_ACCT_REL PRIMARY KEY (ID)
);


-- 银行渠道关系表
CREATE TABLE RXT.T_PAYMENT_CHANNEL_BANK
(
	-- ID
	ID varchar2(20 char) NOT NULL,
	-- 支付通道代码
	PAY_CHANNEL_ID varchar2(20 char),
	-- 银行代码
	BANK_CODE varchar2(20 char),
	-- 支持账户类型（1-对私；2-对公）
	SUPPORT_ACCT_TYPE varchar2(2 char),
	-- 是否支持信用卡（0-否；1-是）
	IS_SUPPORT_CREDIT_CARD varchar2(2 char),
	-- rxt银行代码
	RXT_BANK_CODE varchar2(20 char),
	-- 支付方式，1-网银支付；2-快捷支付
	PAY_MODE varchar2(2 char),
	-- 可用状态，0-未使用；1-使用中
	AVAILABLE_STATE varchar2(2 char) DEFAULT '''0''',
	-- 备注，说明
	REMARK varchar2(200 char),
	-- 单笔限额
	SINGLE_LIMIT varchar2(14 char),
	-- 当天累计限额
	DAILY_LIMIT varchar2(14 char),
	CONSTRAINT PK_T_PAYMENT_CHANNEL_BANK PRIMARY KEY (ID)
);



/* Comments */

COMMENT ON TABLE RXT.T_PAYMENT_CHANNEL IS '支付渠道表';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL.ID IS '主键';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL.PAY_CHANNEL_ID IS '支付通道代码';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL.PAY_CHANNEL_NAME IS '支付通道名称';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL.PAY_MODE IS '支付方式，1-网银支付；2-快捷支付;5-扫码支付';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL.FEE_RATE IS '第三方支付默认手续费率';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL.MAX_FEE IS '默认手续费上限（单位：分）';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL.MIN_FEE IS '默认手续费下限（单位：分）';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL.SETTLE_DAYS IS '清算天数';
COMMENT ON TABLE RXT.T_PAYMENT_CHANNEL_ACCT_REL IS '渠道与结算账户关系表';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL_ACCT_REL.ID IS '主键ID';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL_ACCT_REL.T_PAYMENT_CHANNEL_ID IS '支付渠道表ID';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL_ACCT_REL.T_ZJGJ_SETTLE_ACCT_ID IS '结算账户信息表ID';
COMMENT ON TABLE RXT.T_PAYMENT_CHANNEL_BANK IS '银行渠道关系表';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL_BANK.ID IS 'ID';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL_BANK.PAY_CHANNEL_ID IS '支付通道代码';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL_BANK.BANK_CODE IS '银行代码';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL_BANK.SUPPORT_ACCT_TYPE IS '支持账户类型（1-对私；2-对公）';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL_BANK.IS_SUPPORT_CREDIT_CARD IS '是否支持信用卡（0-否；1-是）';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL_BANK.RXT_BANK_CODE IS 'rxt银行代码';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL_BANK.PAY_MODE IS '支付方式，1-网银支付；2-快捷支付';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL_BANK.AVAILABLE_STATE IS '可用状态，0-未使用；1-使用中';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL_BANK.REMARK IS '备注，说明';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL_BANK.SINGLE_LIMIT IS '单笔限额';
COMMENT ON COLUMN RXT.T_PAYMENT_CHANNEL_BANK.DAILY_LIMIT IS '当天累计限额';



